# ports: HOST:CONTAINER

version: '3.8' 
services:
    nginx:
        image: nginx:alpine
        container_name: ${APP_NAME}-nginx
        restart: unless-stopped
        volumes:
            - ./app/:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        environment:
            - VIRTUAL_HOST=${APP_URL}
            - VIRTUAL_PORT=80
        networks:
            - nproxy
            - lemp-network-${APP_NAME}
            
    php:
        build: .
        container_name: ${APP_NAME}-php8
        restart: always
        depends_on:
            - mongo
            - nginx
        networks:
            - lemp-network-${APP_NAME}      
           
    mongo:
        image: mongo
        container_name: ${APP_NAME}-mongo
        restart: always
        ports:
            - ${MONGO_EXPOSE_PORT}:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
            - VIRTUAL_HOST=${DB_URL}
            - VIRTUAL_PORT=27017
        volumes:
            - ./mongo/data:/data/db
        networks:
            - lemp-network-${APP_NAME}
            - nproxy


networks:
    nproxy:
        external:
          name: nginx-proxy-net 
    lemp-network-${APP_NAME}:
        driver: bridge
